### ISSUE TITLE
add source link in the output html

### ISSUE THREAD

**Issue by hellodword** [wabarc/cairn#383]
I'm using this tool as a replacement of archivebox for wechat's articles because of https://github.com/ArchiveBox/ArchiveBox/issues/318

It works well, but I think we can add the source link, such as singlefile:

```html
<!--
 Page saved with SingleFile 
 url: https://github.com/some/page
 saved date: Sun Feb 06 2022 10:14:13 GMT+0000 (Coordinated Universal Time)
-->
```

**Comment by waybackarchiver** [comment]
In this scenario, if this comment is added to the file, IPFS will not recognize the content as HTML. Compare the [uncommented](https://ipfs.io/ipfs/bafkreig2j7pcmftdyejyonhymk5p77cbukd6m7bil2dlcpzm5xdve2kiji) and [commented](https://ipfs.io/ipfs/bafkreih4k4juenahbdt5rlby7x5od5ggj2xyl5b7jv3c62gnp6gmunok6u) versions for more information.

What about putting the source link inside the meta, like [rivet](https://github.com/wabarc/rivet/blob/ed329cb9369c70e48cac6852cb276db830229f52/internal/obelisk/process-html.go#L176-L179)?

**Comment by hellodword** [comment]
Yes, putting them inside the meta is better.

**Comment by hellodword** [comment]
Oh I see, the `setSource` already done this. 

https://github.com/wabarc/cairn/blob/651c1266b88b61d8de749bc374a84e65faadeef8/src/html.ts#L456-L466

Sorry I didn't look into the source code.
