### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by jlarmstrongiv** [wabarc/cairn#681]
`obelisk`, the original package `cairn` is based on, is licensed under the MIT license.  

`monolith`, which `obelisk` is based on, is licensed under CC0 (public domain).  

Would you consider a less restrictive license?

**Comment by waybackarchiver** [comment]
In the beginning, licensing wasn't a big concern for us and we've just gone straight to licensing the [project-template](/wabarc/project-template). We reconsidered and decided to change the cairn and other base libraries to a **less restrictive licence**, and this change will happen gradually.

**Comment by jlarmstrongiv** [comment]
@waybackarchiver 

What are the steps to relicensing this library?  Which permissive license do you prefer?

It seems to me:
- The original project template may also need to be relicensed https://github.com/wabarc/project-template
- As you are the only contributor according to github insights on both repos, you have all the necessary rights to re-license one or both projects
- PRs to both repos with a new license and your approval should resolve this issue

**Comment by waybackarchiver** [comment]
Resolved

**Comment by jlarmstrongiv** [comment]
Thank you @waybackarchiver 🎉
